### ISSUE TITLE
Code licence

### ISSUE THREAD

**Issue by smarthorizons** [MAX-dev2020/Sleeperly#1]
Hello

Thanks for the app. 
Is this code available openly for use. Can I use it?

**Comment by MAX-dev2020** [comment]
> Hello
> 
> Thanks for the app. 
> Is this code available openly for use. Can I use it?
> 
> 

Thank you for your interest in the code. Yes, this code is available openly for use. However, I kindly request that you use it only for personal purposes and not for commercial projects. Your understanding and cooperation are greatly appreciated.

**Comment by smarthorizons** [comment]
Hi ,

Thanks, but i wanted to use it for commercial use. I don't understand why you don't agree for commercial use. I don't see any difference. Any way, if you don't agree, i will not use it.

**Comment by MAX-dev2020** [comment]
You are welcome to use the logic and code from the app for your personal projects, but I kindly request that you do not use the complete design and layout. Please feel free to modify the code and adapt it to your own needs, but avoid using the entire design for any commercial purposes.

**Comment by MAX-dev2020** [comment]
> Hi ,
> 
> Thanks, but i wanted to use it for commercial use. I don't understand why you don't agree for commercial use. I don't see any difference. Any way, if you don't agree, i will not use it.

You are welcome to use the logic and code from the app for your projects, but I kindly request that you do not use the complete design and layout. Please feel free to modify the code and adapt it to your own needs, but avoid using the entire design for any commercial purposes.

**Comment by smarthorizons** [comment]
Thanks, I will not use the entire design, only the functions with some modifications to suit my needs, I will develop my own UI.
